- name: Copying the redis file
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Installing redis
  ansible.builtin.package:
    name: redis
    state: present

- name: Update mongodb configuration
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restarting the redis service
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes

- name: Setting up hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname